// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGr7b3nD8OYmh-BK21JFf_tK_YPEUIYIg',
    appId: '1:999000695888:android:85b8fcea061f3759879d55',
    messagingSenderId: '999000695888',
    projectId: 'whatsapp-clone-112e0',
    storageBucket: 'whatsapp-clone-112e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIllNEScg8oJ1j4Cfrb6KhmokoC1aO8Kg',
    appId: '1:999000695888:ios:b112d18f823241a1879d55',
    messagingSenderId: '999000695888',
    projectId: 'whatsapp-clone-112e0',
    storageBucket: 'whatsapp-clone-112e0.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGmIRLix6abKE777-dBAE3alnGAOnvlRQ',
    appId: '1:999000695888:web:f8057a6991247508879d55',
    messagingSenderId: '999000695888',
    projectId: 'whatsapp-clone-112e0',
    authDomain: 'whatsapp-clone-112e0.firebaseapp.com',
    storageBucket: 'whatsapp-clone-112e0.firebasestorage.app',
    measurementId: 'G-L0RT93YTWR',
  );
}
